#!/bin/bash
# ESXi VM Creation Guide Script
# Provides step-by-step VM creation instructions

echo "=== ESXi VM Creation Guide ==="
echo ""
echo "This guide provides instructions for creating VMs in your ESXi environment."
echo ""
echo "Prerequisites:"
echo "1. ESXi 6.5u3 installed on both hosts"
echo "2. vSphere Client connected to hosts"
echo "3. Network configured (see docs/network-config.md)"
echo "4. OS installation ISOs available"
echo ""
echo "VM Creation Steps:"
echo "1. Open vSphere Client and connect to ESXi host"
echo "2. Right-click on host → 'Create/Register VM'"
echo "3. Select 'Create a new virtual machine'"
echo "4. Configure VM with specifications from docs/vm-configurations.md"
echo "5. Select appropriate port group (Cluster-A or Cluster-B)"
echo "6. Install operating system from ISO"
echo "7. Install VMware Tools"
echo "8. Configure static IP address"
echo "9. Run configuration script from configs/ directory"
echo ""
echo "For detailed specifications, see:"
echo "- docs/vm-configurations.md"
echo "- docs/esxi-setup.md"
echo "- docs/network-config.md"
